version: "3.7"

networks:
    example:
        external: true

services:
    hello-world:
        deploy:
            mode: global
        image: "${IMAGE_TAG:?}"
        labels:
            traefik.enable: "true"
            traefik.http.services.hello-world.loadbalancer.server.port: 8080
            traefik.http.middlewares.https-only.redirectscheme.scheme: "https"
            traefik.http.routers.hello-world.rule: "Host(`hello-world.salamandra.powerman.name`)"
            traefik.http.routers.hello-world.middlewares: "https-only"
            traefik.http.routers.hello-world-tls.rule: "Host(`hello-world.salamandra.powerman.name`)"
            traefik.http.routers.hello-world-tls.tls: "true"
            traefik.http.routers.hello-world-tls.service: "hello-world"
        networks:
            example:
