version: "3.7"

networks:
    example:
        external: true

services:
    hello-world:
        deploy:
            mode: global
        image: "${IMAGE_TAG:?}"
        labels:
            traefik.enable: "true"
            traefik.http.routers.hello-world.entrypoints: "http,https"
            traefik.http.routers.hello-world.rule: "Host(`hello-world.salamandra.powerman.name`)"
            traefik.http.services.hello-world.loadbalancer.server.port: 8080
        networks:
            example:
